captcha:
    height: 80
    width: 240
    length: 6
    max_skew: 0.7
    dot_count: 80
email:
    host: smtp.qq.com
    port: 465
    from: 1535844075@qq.com
    nickname: xili_blog
    secret: xglxthhjxyechcaa
    is_ssl: true
es:
    url: http://127.0.0.1:9200
    username: ""
    password: ""
    is_console_print: true
gaode:
    enable: true
    key: 66f3c47afb879b2f8eefe49729ea20b1
jwt:
    access_token_secret: ImBBsHvgODPAdfQbhwI-1YnQWuwD6hG11Ams7h3DMr8=
    refresh_token_secret: 1oCGX6VW94ogXTOdtKLTemA5yRBTJcO5i5y9XZm8IU8=
    access_token_expiry_time: 2h
    refresh_token_expiry_time: 7d
    issuer: go_blog
mysql:
    host: 127.0.0.1
    port: 3306
    config: charset=utf8mb4&parseTime=True&loc=Local
    db_name: blog_db
    username: root
    password: root
    max_idle_conns: 10
    max_open_conns: 100
    log_mode: info
qiniu:
    zone: z0
    bucket: xili-blog
    img_path: http://image.xlybd.com/
    access_key: qZlw7PQOGt-QbxvZ7HZ6WchsQ-pOmY6Togow5LdT
    secret_key: rRLlXm3_gG5e74kxP8vJpwXX2cGbBdwZKWWLTUOR
    use_https: true
    use_cdn_domains: true
qq:
    enable: true
    app_id: "102731838"
    app_key: Z1LUQWQ8boobCamj
    redirect_uri: http://xlybd.com/login?flag=qq
redis:
    address: 127.0.0.1:6379
    password: ""
    db: 0
system:
    host: 0.0.0.0
    port: 8080
    env: release
    router_prefix: api
    use_multipoint: true
    sessions_secret: fxOzDD5PlH0IivDao_gJaWUtG_xiEgjLmIlHUNuvSlc=
    oss_type: local
upload:
    size: 20
    path: uploads
website:
    logo: ""
    full_logo: ""
    title: 析离的个人博客
    slogan: 析离
    slogan_en: Graxil
    description: Get busy living or get busy dying
    version: 1.0.0
    created_at: "2025-1-5"
    icp_filing: "京ICP备2025113079号"
    public_security_filing: ""
    bilibili_url: 
    gitee_url: https://gitee.com/xlybd
    github_url: https://github.com/xlybd
    name: 析离
    job: 运维
    address: 北京
    email: 1535844075@qq.com
    qq_image: ""
    wechat_image: ""
zap:
    level: info
    filename: log/go_blog.log
    max_size: 200
    max_backups: 30
    max_age: 5
    is_console_print: true